blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/tsightler/ring-mqtt/discussions/categories/feature-requests
    about: Please check the Feature Requests discussion group and create a new topic there if one does not already exist.
